In [1]:
import numpy as np

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [50]:
a=np.array([[10,20,30],[11,12,13]])
b=np.array([[1,2,3],[4,5,6]])

In [53]:
print(a<b)

[[False False False]
 [False False False]]


In [54]:
print(b<a)

[[ True  True  True]
 [ True  True  True]]


In [5]:
print(a*b)

[[10 40 90]
 [44 60 78]]


In [13]:
c=a*b
print(c)

[[10 40 90]
 [44 60 78]]


In [15]:
print(c.min())

10


In [16]:
print(c.max())

90


In [17]:
print(c.sum())

322


In [55]:
print(len(c))
print(c.max())
print(c.min())
print(c.sum())
print("Dimension:",c.ndim)
print(c.size)
print(c.shape)
print(c.reshape(3,2))
print(c.reshape(6,1))
print(c.reshape(1,6))
print(c.mean())
print(np.median(c))
print(np.std(c))
print(c.var())
print(np.prod(c))
print(np.cumsum(c))
print(c>50)
print(c<80)
print(c==10)

2
90
10
322
Dimension: 2
6
(2, 3)
[[10 40]
 [90 44]
 [60 78]]
[[10]
 [40]
 [90]
 [44]
 [60]
 [78]]
[[10 40 90 44 60 78]]
53.666666666666664
52.0
26.265736024122546
689.8888888888888
7413120000
[ 10  50 140 184 244 322]
[[False False  True]
 [False  True  True]]
[[ True  True False]
 [ True  True  True]]
[[ True False False]
 [False False False]]


In [68]:
a = np.array([2, 4, 6])
b = np.array([1, 2, 3])
print("Addition:",a+b)
print("Multiplication:",a*b)
print("Product:",np.prod(a))
print("Prduct:",np.prod(b))
print(a**2)
print(b**2)
print(a.sum())
print(a.mean())
print(a > 3)
print(b > 3)
print(a<3)
print(b<3)


Addition: [3 6 9]
Multiplication: [ 2  8 18]
Product: 48
Prduct: 6
[ 4 16 36]
[1 4 9]
12
4.0
[False  True  True]
[False False False]
[ True False False]
[ True  True False]


In [70]:
a = np.array([
    [2,4,6],
    [8,10,12]
])

In [77]:
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))
print(a.mean(axis=0))
print(a.mean(axis=1))
print(a.max(axis=0))
print(a.min(axis=1))

42
[10 14 18]
[12 30]
[5. 7. 9.]
[ 4. 10.]
[ 8 10 12]
[2 8]


In [2]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
print(numbers)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
numbers=np.zeros((3,4))
print(numbers)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
numbers=np.ones((4,4))
print(numbers)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
numbers=np.eye((5))
print(numbers)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
numbers=np.arange(5,51,5)
print(numbers)

[ 5 10 15 20 25 30 35 40 45 50]


In [ ]:
numbers=np.linspace(0,1,8)
print(numbers)


[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]


In [22]:
numbers=np.linspace(5,51,5)
print(numbers)

[ 5.  16.5 28.  39.5 51. ]


In [25]:
#Find the shape of an array.
numbers=np.array([[1,2,3],[4,5,6]])
numbers.shape

(2, 3)

In [26]:
#Find the number of dimensions using ndim.
numbers.ndim

2

In [27]:
#Find the total number of elements using size.
numbers.size

6

In [29]:
#Find the datatype of an array.
numbers.dtype


dtype('int64')

In [31]:
type(numbers)

numpy.ndarray

In [32]:
#Convert an integer array into a float array.
numbers=np.array([[1,2,3],[4,5,6]],dtype=float)
print(numbers)

[[1. 2. 3.]
 [4. 5. 6.]]


In [35]:
numbers=np.array([1,2,3,4,5,6])
numbers.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
numbers=np.array([[[1,2,3,4],
                  [5,6,7,8]],
                  [[9,8,7,10],
                   [11,12,13,13]]
                 ] )
print(numbers.shape)

(2, 2, 4)


In [40]:
numbers=np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,7,8,10]
                 ] )

In [41]:
print(numbers.shape)

(3, 4)


In [42]:
print(numbers.reshape((4,3)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 7  8 10]]


In [5]:
print(numbers.resize((4,3)))

None


**Part 4: Indexing and Slicing (Very Important)**

In [30]:
#Print the first three elements of an array.
numbers=np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,7,8,10]
                 ] )

numbers[0][0:3]


array([1, 2, 3])

In [10]:
numbers[2][1:]

array([ 7,  8, 10])

In [11]:
#Reverse an array using slicing.
numbers[::-1]

array([[ 9,  7,  8, 10],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [12]:
#Extract the second row from a 2D array.
numbers[1]

array([5, 6, 7, 8])

In [32]:
print(numbers[0][2],numbers[1][2],numbers[2][2])
print(numbers[:,-2])

3 7 8
[3 7 8]


In [6]:
numbers=np.array([[10,20, 30],
                  [40,50, 60],
                  [70 ,80 ,90]])
print(numbers)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [7]:
numbers[:,-2][0:2],numbers[:,-1][0:2]

(array([20, 50]), array([30, 60]))

In [54]:
print(numbers[0][1:],numbers[1][1:])

[20 30] [50 60]


**Part 5: Boolean Indexing**

In [8]:
number=numbers[numbers>50]
print(number)

[60 70 80 90]


In [11]:
number=numbers[numbers>60]
print(number)

[70 80 90]


In [22]:
#Replace all values greater than 30 with 0.
number=numbers[numbers>30]=0
print(numbers)


[[10 20 30]
 [ 0  0  0]
 [ 0  0  0]]


In [26]:
number=numbers[numbers<20]=0
print(numbers)

[[ 0 20 30]
 [ 0  0  0]
 [ 0  0  0]]


0


In [84]:
numbers=np.array([[10,20, 30],
                  [40,50, 60],
                  [70 ,80 ,91]])

In [56]:
number=np.where(numbers%2==0,numbers,None)
print(number)


[[10 None 30]
 [40 50 60]
 [70 80 None]]


In [57]:
number=numbers[numbers%2==0]
print(number)

[10 30 40 50 60 70 80]


In [81]:
number=np.isin(numbers,[20,70])
print(number)

[[False False False]
 [False False False]
 [ True False False]]


In [85]:
number=numbers[np.isin(numbers,[20,70])]
print(number)

[20 70]


In [87]:
number=numbers[(numbers > 20) & (numbers < 70)]
print(number)

[30 40 50 60]


In [90]:
number=numbers[numbers%2 != 0]
print(number)

[91]


In [92]:
arr = np.array([10, 15, 20, 25, 30, 35])
number=arr[arr%2 != 0]
print(number)


[15 25 35]


In [93]:
#Replace all negative numbers with 0
arr=np.array([-5,10,-2,7,-9,4])

In [106]:
number=arr[(arr<0)]
print(arr)

[ 0 10  0  7  0  4]


In [108]:
number=arr[arr<0]=0
print(arr)

[ 0 10  0  7  0  4]


In [26]:
import numpy as np

arr = np.array([5, 12, 18, 25, 30, 35, 42, 50, 55, 60, 68, 75, 80, 95, 100])

In [3]:
numbers=arr[arr>50]
print(numbers)

[ 55  60  68  75  80  95 100]


In [5]:
#Print all values less than 30.
numbers=arr[arr<30]
print(numbers)

[ 5 12 18 25]


In [8]:
#Print all even numbers from the array.
numbers=arr[arr%2==0]
print(numbers)

[ 12  18  30  42  50  60  68  80 100]


In [9]:
#Print all odd numbers from the array.
numbers=arr[arr%2 != 0]
print(numbers)

[ 5 25 35 55 75 95]


In [14]:
#Print all numbers between 20 and 70 (inclusive).
numbers=arr[(arr>=20) & (arr<=70)]
print(numbers)

[25 30 35 42 50 55 60 68]


In [17]:
#Replace all values greater than 60 with 0.
numbers=arr[arr>60]=0
print(arr)

[ 5 12 18 25 30 35 42 50 55 60  0  0  0  0  0]


In [24]:
numbers=arr[arr%2==0]=-1
print(arr)

[ 5 -1 -1 25 -1 35 -1 -1 55 -1 -1 75 -1 95 -1]


In [27]:
numbers=arr[arr % 5==0]
print(numbers)

[  5  25  30  35  50  55  60  75  80  95 100]


In [30]:
numbers=arr[(arr>=20) & (arr<=80)]
print(numbers)

[25 30 35 42 50 55 60 68 75 80]


In [56]:
arr = np.array([5, 12, 18, 25, 30, 35, 42, 50, 55, 60, 68, 75, 80, 95, 100])

In [40]:
numbers=arr[(arr<=20) | (arr>=80)]
print(numbers)

[  5  12  18  80  95 100]


In [54]:
#Replace all numbers divisible by 10 with 999.
numbers=arr[arr %10]=999
print(arr)

[999  12 999  25  30 999  42  50 999  60  68  75  80  95 100]


In [52]:
#Print numbers that are divisible by 2 and 3.
numbers=arr[(arr%2==0) & (arr%3==0)]
print(numbers)

[12 18 30 42 60]


In [57]:
#Print numbers that are not divisible by 5.
numbers = arr[arr % 5 !=0]
print(numbers)

[12 18 42 68]


In [59]:
#Replace all numbers between 40 and 80 with 100.
numbers=arr[(arr>=40) & (arr<=80)]=100
print(arr)

[  5  12  18  25  30  35 100 100 100 100 100 100 100  95 100]


In [62]:
#Print numbers that are greater than 30 and are even.
numbers=arr[(arr>30) & (arr %2 ==0)]
print(numbers)

[100 100 100 100 100 100 100 100]


In [3]:
import numpy as np
a=np.array([[10,20 ,30],
 [40 ,50 ,60],
 [70 ,80 ,90]])

In [18]:
print(np.where(a==10)[1])
print(np.where(a==30)[1])
print(np.where(a==60)[1])

[0]
[2]
[2]


In [37]:
import numpy as np

arr = np.array([5, 12, 18, 25, 30, 35, 42])

In [35]:
print(arr[[0,2,4]])

[ 5 18 30]


In [39]:
print(arr[[1,3,5]])

[12 25 35]


In [41]:
print(arr[[0,-1]])

[ 5 42]


In [42]:
print(arr[[0,4,6]])

[ 5 30 42]


In [44]:
print(arr[[2,5]])

[18 35]


In [46]:
print(arr[[1,2,6]])

[12 18 42]


In [52]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

In [84]:
import pandas as pd

In [54]:
print(arr[[0,2]])

[[10 20 30]
 [70 80 90]]


In [58]:
print(arr[[0,-2]])

[[10 20 30]
 [40 50 60]]


In [59]:
print(arr[[1,2]])

[[40 50 60]
 [70 80 90]]


In [60]:
print(arr[[2,0]])

[[70 80 90]
 [10 20 30]]


In [ ]:
print(arr[[0,1,2]][0])

[[10 20 30]]


In [90]:
print(arr[:,[0,1]])

[[10 20]
 [40 50]
 [70 80]]


In [87]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

In [92]:
number=arr[arr>50]
print(number)

[60 70 80 90]


In [96]:
num=arr[(arr>=30) & (arr<=80)]
print(num)

[30 40 50 60 70 80]


In [98]:
num=arr[(arr<=30) | (arr<=80)]
print(num)

[10 20 30 40 50 60 70 80]


In [101]:
print(arr[:,[0,2]])

[[10 30]
 [40 60]
 [70 90]]


In [105]:
print(arr[:,[1,2]])
print(arr[:,[2,0]])

[[20 30]
 [50 60]
 [80 90]]
[[30 10]
 [60 40]
 [90 70]]


In [115]:
print(arr[0,[0]],arr[1,[1]],arr[2,[2]])

[10] [50] [90]


In [ ]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

In [143]:
print(arr[[0,1,2],[0,1,2]])

[10 50 90]


In [121]:
print(arr[0,[1]],arr[1,[2]],arr[2,[2]])

[20] [60] [90]


In [140]:
print(arr[[0,1,2],[1,2,2]])

[20 60 90]


In [126]:
print(arr[[0,2],:])

[[10 20 30]
 [70 80 90]]


In [135]:
print(arr[[0,0,2,2],[0,2,0,2]])

[10 30 70 90]


In [ ]:
# (0, 0) → 10
# (0, 2) → 30
# (2, 0) → 70
# (2, 2) → 90

In [124]:
print(arr[0,[0,2]],arr[2,[0,2]])

[10 30] [70 90]
